document.getElementById('get-btn').addEventListener('click', generateThumbnails);

function extractVideoId(url) {
  // RegEx pattern to match standard YouTube URLs, Shorts, and shortened links (youtu.be)
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
  const match = url.match(regExp);

  return (match && match[2].length === 11) ? match[2] : null;
}

function generateThumbnails() {
  const urlInput = document.getElementById('video-url').value.trim();
  const errorMsg = document.getElementById('error-msg');
  const resultsDiv = document.getElementById('results');

  const videoId = extractVideoId(urlInput);

  if (!videoId) {
    errorMsg.classList.remove('hidden');
    resultsDiv.classList.add('hidden');
    return;
  }

  errorMsg.classList.add('hidden');

  // Thumbnail URLs generated by YouTube's static server
  const maxresUrl = `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`;
  const sdUrl = `https://img.youtube.com/vi/${videoId}/sddefault.jpg`;
  const mqUrl = `https://img.youtube.com/vi/${videoId}/mqdefault.jpg`;

  // Set Image sources
  document.getElementById('img-maxres').src = maxresUrl;
  document.getElementById('img-sd').src = sdUrl;
  document.getElementById('img-mq').src = mqUrl;

  // Set Download Links
  document.getElementById('download-maxres').href = maxresUrl;
  document.getElementById('download-sd').href = sdUrl;
  document.getElementById('download-mq').href = mqUrl;

  // Show the results
  resultsDiv.classList.remove('hidden');
}
